# Generated by Django 5.0 on 2024-02-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='student',
            name='type',
        ),
        migrations.AddField(
            model_name='student',
            name='allergy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='cleanliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='lights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='overnight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='quite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='selfcontained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sharing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='study',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
    ]
