# Generated by Django 5.0 on 2024-02-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_nature_remove_student_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
