# Generated by Django 4.2.11 on 2025-04-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
