# Generated by Django 4.2.11 on 2025-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_student_allergy_alter_student_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
