# Generated by Django 4.2.11 on 2025-11-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_alter_student_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('extraversion', models.FloatField(blank=True, null=True)),
                ('agreeableness', models.FloatField(blank=True, null=True)),
                ('conscientiousness', models.FloatField(blank=True, null=True)),
                ('neuroticism', models.FloatField(blank=True, null=True)),
                ('openness', models.FloatField(blank=True, null=True)),
                ('student_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
